version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: dev

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    target-branch: dev

  - package-ecosystem: npm
    directory: /react
    schedule:
      interval: weekly
    target-branch: dev
