PREAMBLE_EXTRACTED = "preamble_extracted"
BODY_EXTRACTED_REGEX = "body_extracted_regex"
BODY_EXTRACTED_LLM = "body_extracted_llm"
GROUND_TRUTH_CURATED = "ground_truth_curated"

DEPENDENCY_APPROACH_ORDER = [
    PREAMBLE_EXTRACTED,
    BODY_EXTRACTED_REGEX,
    BODY_EXTRACTED_LLM,
    GROUND_TRUTH_CURATED,
]

DEPENDENCY_PAIRWISE_COMPARISON_ORDER = [
    PREAMBLE_EXTRACTED,
    BODY_EXTRACTED_REGEX,
    BODY_EXTRACTED_LLM,
]

DEPENDENCY_APPROACH_SHORT_LABELS = {
    PREAMBLE_EXTRACTED: "Preamble",
    BODY_EXTRACTED_REGEX: "Regex",
    BODY_EXTRACTED_LLM: "LLM",
    GROUND_TRUTH_CURATED: "Ground Truth",
}

DEPENDENCY_APPROACH_LABELS = {
    PREAMBLE_EXTRACTED: "Preamble-Extracted Dependencies",
    BODY_EXTRACTED_REGEX: "Body-Extracted Dependencies (Regex)",
    BODY_EXTRACTED_LLM: "Body-Extracted Dependencies (LLM)",
    GROUND_TRUTH_CURATED: "Ground Truth (Human-Curated)",
}
